config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from config import settings

urlpatterns = [
    # MAIN URLS
    path('controlme/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('profiller/', include('profiles.urls')),

    # Reset password urls
    path('sifre-sifirla/', auth_views.PasswordResetView.as_view(template_name='profiles/password_reset.html',
                                                                email_template_name='profiles/password_reset_email.html',
                                                                subject_template_name='profiles/password_reset_subject.txt'), name='password_reset'),
    path('sifre-gonderildi/', auth_views.PasswordResetDoneView.as_view(template_name='profiles/password_reset_done.html'), name='password_reset_done'),
    path('sifre-onayla/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='profiles/password_reset_confirm.html'), name='password_reset_confirm'),
    path('sifre-sifirlandi/', auth_views.PasswordResetCompleteView.as_view(template_name='profiles/password_reset_complete.html'), name='password_reset_complete'),

    # ADDITIONAL URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from profiles import views
from profiles.views import SignUpView, JobSeekerSignUpView, RecruiterSignUpView, \
    JobSeekerProfileUpdateView, JobSeekerProfileView, RecruiterProfileView, RecruiterProfileUpdateView
from django.contrib.auth import views as auth_views


app_name = 'profiles'
urlpatterns = [
    # Log-in and Logout
    path('kayit/', SignUpView.as_view(), name='signup'),
    path('kayit/is-arayan/', JobSeekerSignUpView.as_view(), name='jobseeker_signup'),
    path('kayit/ik-uzmani/', RecruiterSignUpView.as_view(), name='recruiter_signup'),
    path('giris-yap/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('cikis-yap/', auth_views.LogoutView.as_view(), name='logout'),

    # Mainsite urls
    path('is-arayan/profil/<slug:slug>/', JobSeekerProfileView.as_view(), name='jobseeker_profile'),
    path('is-arayan/guncelle/<slug:slug>/', JobSeekerProfileUpdateView.as_view(), name='jobseeker_profile_update'),
    path('ik-uzmani/profil/<slug:slug>/', RecruiterProfileView.as_view(), name='recruiter_profile'),
    path('ik-uzmani/guncelle/<slug:slug>/', RecruiterProfileUpdateView.as_view(), name='recruiter_profile_update'),
    path("ilana-basvur/<int:job_id>/", views.apply_job_view, name="apply_job"),
]

profiles/models/jobseeker.py
from django.db import models
from django.core.validators import FileExtensionValidator
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill, Transpose
from profiles.models.skills import Skill
from django.utils.text import slugify
from django.urls import reverse
from profiles.models import Profile


class JobSeeker(models.Model):
    is_active = models.BooleanField("Durum (Aktif/Pasif)", default=True)
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, verbose_name="Profil", primary_key=True)
    email = models.EmailField("Email Adresi", unique=True)
    first_name = models.CharField("İsim", max_length=50)
    last_name = models.CharField("Soyisim", max_length=50)
    phone = models.CharField("Telefon", max_length=15, help_text="Zorunlu alan değildir.", blank=True)
    country = models.CharField("Ülke", max_length=50)
    city = models.CharField("Şehir", max_length=50, blank=True)
    avatar = models.ImageField("Profil Resmi", upload_to='img/avatars/', help_text="Zorunlu alan değildir.", blank=True, null=True)
    avatar_thumbnail_140x140 = ImageSpecField(source='avatar', processors=[Transpose(), ResizeToFill(140, 140)], format='WEBP', options={'quality': 80})
    profession_title = models.CharField("Başlık/Uzmanlık Alanı", help_text="Ör: Django Geliştirici", max_length=200)
    skills = models.ManyToManyField(Skill, verbose_name="Beceri Adı", related_name="profiles")
    short_resume = models.TextField("Kısa Özgeçmiş", max_length=500, help_text="Kısa özgeçmiş alanı zorunlu değildir.", blank=True)
    cv_file = models.FileField("CV", upload_to='cv_files/', help_text='Desteklenen Dosya Formatı: pdf, doc, docx', blank=True, null=True,
                               validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])
    slug = models.SlugField("Slug", help_text="Bu alan otomatik olarak oluşturulmaktadır.", max_length=60, unique=True, allow_unicode=True)
    updated = models.DateTimeField("Güncellenme Tarihi", auto_now=True)
    date_joined = models.DateTimeField("Oluşturulma Tarihi", auto_now_add=True)

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.pk) + "-" + self.first_name + "-" + self.last_name)
        super(JobSeeker, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('profiles:jobseeker_profile', args=[self.slug])

    class Meta:
        verbose_name_plural = "İş Arayanlar"
        verbose_name = "İş Arayan"
        ordering = ("-date_joined",)

profiles/models/permissions.py
from django.core.exceptions import PermissionDenied


def user_is_jobseeker(function):  # If the user is not the jobseeker, it will show the 403 error page.
    def wrap(request, *args, **kwargs):
        if request.user.is_active and request.user.is_jobseeker:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied
    return wrap


def user_is_recruiter(function):  # If the user is not the recruiter, it will show the 403 error page.
    def wrap(request, *args, **kwargs):
        if request.user.is_active and request.user.is_recruiter:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied
    return wrap

profiles/models/profiles.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Profile(AbstractUser):
    is_jobseeker = models.BooleanField('Kullanıcı mı?', default=False)
    is_recruiter = models.BooleanField('IK Uzmanı mı?', default=False)

    class Meta:
        verbose_name_plural = "Profiller"
        verbose_name = "Profil"

profiles/models/skills.py
from django.db import models


class Skill(models.Model):
    skill_name = models.CharField("Beceri Adı", max_length=100)

    def __str__(self):
        return self.skill_name

    class Meta:
        verbose_name_plural = "Beceriler"
        verbose_name = "Beceri"
        ordering = ("skill_name", )

profiles/forms/applyjob_form.py
from django import forms
from mainsite.models.applicants import Applicants


class ApplyJobForm(forms.ModelForm):
    class Meta:
        model = Applicants
        fields = ("job",)

profiles/forms/jobseeker_signup_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from profiles.models import Profile, JobSeeker, Skill


class JobSeekerSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True, label="İsim")
    last_name = forms.CharField(required=True, label="Soyisim")
    phone = forms.CharField(required=False, label="Telefon")
    country = forms.CharField(required=True, label="Ülke")
    city = forms.CharField(required=False, label="Şehir")
    avatar = forms.ImageField(required=False, label="Profil Resmi")
    profession_title = forms.CharField(required=True, label="Başlık/Uzmanlık Alanı")
    skills = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Beceriler"
    )
    short_resume = forms.CharField(widget=forms.Textarea, required=False, label="Kısa Özgeçmiş")
    cv_file = forms.FileField(required=False, label="CV")

    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_jobseeker = True
        user.save()
        jobseeker = JobSeeker.objects.create(profile=user)
        jobseeker.email = self.cleaned_data.get('email')
        jobseeker.first_name = self.cleaned_data.get('first_name')
        jobseeker.last_name = self.cleaned_data.get('last_name')
        jobseeker.phone = self.cleaned_data.get('phone')
        jobseeker.country = self.cleaned_data.get('country')
        jobseeker.city = self.cleaned_data.get('city')
        jobseeker.avatar = self.cleaned_data.get('avatar')
        jobseeker.profession_title = self.cleaned_data.get('profession_title')
        jobseeker.skills.add(*self.cleaned_data.get('skills'))
        jobseeker.short_resume = self.cleaned_data.get('short_resume')
        jobseeker.cv_file = self.cleaned_data.get('cv_file')
        jobseeker.slug = self.cleaned_data.get('slug')
        jobseeker.save()
        return user

profiles/forms/recruiter_signup_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from profiles.models import Profile, Recruiter


class RecruiterSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True, label="İsim")
    last_name = forms.CharField(required=True, label="Soyisim")
    phone = forms.CharField(required=False, label="Telefon")
    country = forms.CharField(required=True, label="Ülke")
    avatar = forms.ImageField(required=False, label="Profil Resmi")
    profession_title = forms.CharField(required=True, label="Başlık/Uzmanlık Alanı")
    company = forms.CharField(required=True, label="Firma")

    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_recruiter = True
        user.save()
        recruiter = Recruiter.objects.create(profile=user)
        recruiter.email = self.cleaned_data.get('email')
        recruiter.first_name = self.cleaned_data.get('first_name')
        recruiter.last_name = self.cleaned_data.get('last_name')
        recruiter.phone = self.cleaned_data.get('phone')
        recruiter.country = self.cleaned_data.get('country')
        recruiter.avatar = self.cleaned_data.get('avatar')
        recruiter.profession_title = self.cleaned_data.get('profession_title')
        recruiter.company = self.cleaned_data.get('company')
        recruiter.slug = self.cleaned_data.get('slug')
        recruiter.save()
        return user

profiles/views/applyjob.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from mainsite.models.applicants import Applicants
from profiles.forms import ApplyJobForm
from django.contrib import messages
from profiles.models import JobSeeker, user_is_jobseeker


@login_required(login_url=reverse_lazy('profiles:login'))
@user_is_jobseeker
def apply_job_view(request, job_id):
    form = ApplyJobForm(request.POST or None)
    user = get_object_or_404(JobSeeker, profile_id=request.user.id)
    applicant = Applicants.objects.filter(applicant__profile=user, job=job_id)

    if not applicant:
        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit=False)
                instance.applicant = user
                instance.save()
                messages.success(
                    request, 'İlana başarıyla başvuru yaptınız!')
                return redirect(request.META.get("HTTP_REFERER"))
        else:
            return redirect(request.META.get("HTTP_REFERER"))
    else:
        messages.error(request, 'Bu ilana zaten başvurmuştunuz!')
        return redirect(request.META.get("HTTP_REFERER"))

profiles/views/jobseeker_profile_details.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from profiles.models import JobSeeker


@method_decorator([login_required(login_url=reverse_lazy("profiles:login"))], name='dispatch')
class JobSeekerProfileView(DetailView):
    model = JobSeeker
    context_object_name = "jobseeker"
    template_name = 'profiles/jobseeker_profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

profiles/views/jobseeker_profile_edit.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from profiles.models import user_is_jobseeker, JobSeeker


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_jobseeker], name='dispatch')
class JobSeekerProfileUpdateView(UpdateView):
    model = JobSeeker
    fields = ('first_name', 'last_name', 'email', 'phone', 'country', 'city', 'avatar', 'profession_title',
              'skills', 'short_resume', 'cv_file')
    context_object_name = "jobseeker"
    template_name = 'profiles/jobseeker_profile_edit.html'

    def form_valid(self, form):
        messages.success(self.request, 'İş arayan bilgileri başarıyla güncellendi!')
        return super().form_valid(form)

profiles/views/jobseeker_signup.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView
from profiles.forms import JobSeekerSignUpForm
from profiles.models import Profile


class JobSeekerSignUpView(CreateView):
    model = Profile
    form_class = JobSeekerSignUpForm
    template_name = 'profiles/jobseeker_signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'jobseeker'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('mainsite:index')

profiles/views/recruiter_profile_details.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from profiles.models import Recruiter, user_is_recruiter


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_recruiter], name='dispatch')
class RecruiterProfileView(DetailView):
    model = Recruiter
    context_object_name = "recruiter"
    template_name = 'profiles/recruiter_profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

profiles/views/recruiter_profile_edit.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from profiles.models import Recruiter, user_is_recruiter


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_recruiter], name='dispatch')
class RecruiterProfileUpdateView(UpdateView):
    model = Recruiter
    fields = ('first_name', 'last_name', 'email', 'phone', 'country', 'avatar', 'profession_title',
              'company')
    context_object_name = "recruiter"
    template_name = 'profiles/recruiter_profile_edit.html'

    def form_valid(self, form):
        messages.success(self.request, 'İş arayan bilgileri başarıyla güncellendi!')
        return super().form_valid(form)

profiles/views/recruiter_signup.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView
from profiles.forms import RecruiterSignUpForm
from profiles.models import Profile


class RecruiterSignUpView(CreateView):
    model = Profile
    form_class = RecruiterSignUpForm
    template_name = 'profiles/recruiter_signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'recruiter'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('mainsite:index')

profiles/views/signup.py
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = "profiles/signup.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

profiles/templates/profiles/jobseeker_profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}İş Arayan Profil Detayları{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Profil Detayları</h1>
                    <div class="col-6 pt-4">
                        <div>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success text-center" role="alert">
                                        {% if message.tags %}
                                            <p>{{ message }}</p>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <img class="img-fluid rounded-start" src="{% get_media_prefix %}{{ jobseeker.avatar_thumbnail_140x140 }}" alt="{{ jobseeker.get_full_name }}">
                            <p><strong>Kullanıcı Adı:</strong> {{ jobseeker.profile }}</p>
                            <p><strong>İsim:</strong> {{ jobseeker.first_name }}</p>
                            <p><strong>Soyisim:</strong> {{ jobseeker.last_name }}</p>
                            <p><strong>Email:</strong> {{ jobseeker.email }}</p>
                            <p><strong>Telefon:</strong> {{ jobseeker.phone }}</p>
                            <p><strong>Ülke:</strong> {{ jobseeker.country }}</p>
                            <p><strong>Şehir:</strong> {{ jobseeker.city }}</p>
                            <p><strong>Başlık/Uzmanlık Alanı:</strong> {{ jobseeker.profession_title }}</p>
                            <p><strong>Beceriler:</strong>
                            {% for skill in jobseeker.skills.all %}
                                {{ skill }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </p>
                            <p><strong>Kısa Özgeçmiş:</strong> {{ jobseeker.short_resume }}</p>
                            <p><strong>CV:</strong> {{ jobseeker.cv_file }}</p>
                            {% if user.is_authenticated and jobseeker.profile.id == user.id %}
                            <a href="{% url 'profiles:jobseeker_profile_update' slug=jobseeker.slug %}" class="btn btn-dark" role="button">Profili Güncelle</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/jobseeker_profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}İş Arayan Profil Güncelleme{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center ">
                    <h1 class="text-center">Profil Güncelle</h1>
                    <div class="col-6 pt-4">
                        {% if jobseeker.profile.id == user.id %}
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-5" type="submit">Güncelle</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/jobseeker_signup_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}İş Arayan Kullanıcı Kaydı{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">İş Arayan Üye Kaydı</h1>
                    <div class="col-6 pt-4">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-5" type="submit">Kayıt Ol</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}Kullanıcı Girişi{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Giriş Yapın</h1>
                    <div class="col-6 pt-4">
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-2" type="submit">Giriş Yap</button>
                        </form>
                    </div>
                    <div class="text-center mb-5">
                        <small>
                            <a href="#" class="text-muted">Şifrenizi mi Unuttunuz?</a>
                        </small>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Şifre Sıfırla{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Şifre Sıfırla</h1>
                    <div class="col-6 pt-4">
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-2" type="submit">Şifre Sıfırlama Talebi Gönder</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Şifre Sıfırlama Emaili Gönderildi{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Şifre Sıfırlama Emaili Gönderildi</h1>
                    <div class="col-6 pt-4">
                        <div class="alert alert-success">
                            Şifreniz başarıyla değiştirildi.
                        </div>
                        <a href="{% url 'profiles:login' %}">Buradan Giriş Yapın</a>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Şifre Sıfırla{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Şifreyi Sıfırla</h1>
                    <div class="col-6 pt-4">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <button class="btn btn-dark mt-3 mb-2" type="submit">Şifreyi Sıfırla</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Şifre Sıfırlama Emaili Gönderildi{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Şifre Sıfırlama Emaili Gönderildi</h1>
                    <div class="col-6 pt-4">
                        <div class="alert alert-success">
                            Parolanızı sıfırlamak için talimatları içeren bir e-posta gönderildi.
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}Bu e-postayı, {{ site_name }} adresindeki kullanıcı hesabınız için bir şifre sıfırlama isteğinde bulunulduğu için alıyorsunuz.{% endblocktranslate %}

{% translate "Lütfen aşağıdaki bağlantıya tıklayarak açılan sayfadan yeni bir şifre belirleyin:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Unutmuş olma ihtimalinize karşı Kullanıcı adınız:' %} {{ user.get_username }}

{% translate "Sitemizi kullandığınız için teşekkürler!" %}

{% blocktranslate %}{{ site_name }} ekibi{% endblocktranslate %}

{% endautoescape %}

profiles/templates/profiles/recruiter_profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}IK Uzmanı Profil Detayları{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Profil Detayları</h1>
                    <div class="col-6 pt-4">
                        <div>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success text-center" role="alert">
                                        {% if message.tags %}
                                            <p>{{ message }}</p>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <img class="img-fluid rounded-start" src="{% get_media_prefix %}{{ recruiter.avatar_thumbnail_140x140 }}" alt="{{ recruiter.get_full_name }}">
                            <p><strong>Kullanıcı Adı:</strong> {{ user.get_username }}</p>
                            <p><strong>İsim:</strong> {{ recruiter.first_name }}</p>
                            <p><strong>Soyisim:</strong> {{ recruiter.last_name }}</p>
                            <p><strong>Email:</strong> {{ recruiter.email }}</p>
                            <p><strong>Telefon:</strong> {{ recruiter.phone }}</p>
                            <p><strong>Ülke:</strong> {{ recruiter.country }}</p>
                            <p><strong>Başlık/Uzmanlık Alanı:</strong> {{ recruiter.profession_title }}</p>
                            <p><strong>Firma:</strong> {{ recruiter.company }}</p>
                            {% if user.is_authenticated and recruiter.profile.id == user.id %}
                            <a href="{% url 'profiles:recruiter_profile_update' slug=recruiter.slug %}" class="btn btn-dark" role="button">Profili Güncelle</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/recruiter_profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}IK Uzmanı Profil Güncelleme{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">Profil Güncelle</h1>
                    <div class="col-6 pt-4">
                        {% if recruiter.profile.id == user.id %}
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-5" type="submit">Güncelle</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

profiles/templates/profiles/signup.html
{% extends 'base.html' %}

{% block title %}Kullanıcı Kaydı{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row text-center">
                    <div class="col">
                        <h1>Üye olun</h1>
                        <p>Lütfen üye olmak için üyelik tipini seçiniz.</p>
                        <div class="d-grid col-2 gap-3 mx-auto">
                            <a href="{% url 'profiles:jobseeker_signup' %}" class="btn btn-dark" role="button">Ben İş Arıyorum</a>
                            <a href="{% url 'profiles:recruiter_signup' %}" class="btn btn-dark" role="button">Ben IK Uzmanıyım</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}