config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from config import settings

urlpatterns = [
    # MAIN URLS
    path('controlme/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('profiller/', include('profiles.urls')),

    # Reset password urls
    path('sifre-sifirla/', auth_views.PasswordResetView.as_view(template_name='profiles/password_reset.html',
                                                                email_template_name='profiles/password_reset_email.html',
                                                                subject_template_name='profiles/password_reset_subject.txt'), name='password_reset'),
    path('sifre-gonderildi/', auth_views.PasswordResetDoneView.as_view(template_name='profiles/password_reset_done.html'), name='password_reset_done'),
    path('sifre-onayla/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='profiles/password_reset_confirm.html'), name='password_reset_confirm'),
    path('sifre-sifirlandi/', auth_views.PasswordResetCompleteView.as_view(template_name='profiles/password_reset_complete.html'), name='password_reset_complete'),

    # ADDITIONAL URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.urls import path
from mainsite.views import IndexView, JobSeekerProfilesView, JobsView, JobDetailView, JobUpdateView, JobCreateView, \
    AppliedApplicantsView, SearchResultsView, RelatedJobsView

app_name = 'mainsite'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('is-arayanlar/', JobSeekerProfilesView.as_view(), name='jobseeker_profiles'),
    path('is-ilanlari/', JobsView.as_view(), name='job_list'),
    path('ilgili-is-ilanlari/', RelatedJobsView.as_view(), name='related_job_list'),
    path('is-ilanlari/ilan-detayi/<slug:slug>/', JobDetailView.as_view(), name='job_details'),
    path('is-ilanlari/ilan-guncelle/<slug:slug>/', JobUpdateView.as_view(), name='job_update'),
    path('is-ilani-ekle/', JobCreateView.as_view(), name='job_create'),
    path('ilan-basvurulari/', AppliedApplicantsView.as_view(), name='applied_applicants_list'),
    path('arama/', SearchResultsView.as_view(), name='search_results'),
]

profiles/urls.py
from django.urls import path
from profiles import views
from profiles.views import SignUpView, JobSeekerSignUpView, RecruiterSignUpView, \
    JobSeekerProfileUpdateView, JobSeekerProfileView, RecruiterProfileView, RecruiterProfileUpdateView
from django.contrib.auth import views as auth_views


app_name = 'profiles'
urlpatterns = [
    # Log-in and Logout
    path('kayit/', SignUpView.as_view(), name='signup'),
    path('kayit/is-arayan/', JobSeekerSignUpView.as_view(), name='jobseeker_signup'),
    path('kayit/ik-uzmani/', RecruiterSignUpView.as_view(), name='recruiter_signup'),
    path('giris-yap/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('cikis-yap/', auth_views.LogoutView.as_view(), name='logout'),

    # Mainsite urls
    path('is-arayan/profil/<slug:slug>/', JobSeekerProfileView.as_view(), name='jobseeker_profile'),
    path('is-arayan/guncelle/<slug:slug>/', JobSeekerProfileUpdateView.as_view(), name='jobseeker_profile_update'),
    path('ik-uzmani/profil/<slug:slug>/', RecruiterProfileView.as_view(), name='recruiter_profile'),
    path('ik-uzmani/guncelle/<slug:slug>/', RecruiterProfileUpdateView.as_view(), name='recruiter_profile_update'),
    path("ilana-basvur/<int:job_id>/", views.apply_job_view, name="apply_job"),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="prefetch stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="prefetch stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="prefetch stylesheet" type="text/css" href="{% static '/css/style.css' %}" />
</head>
<body>
    <header>
        <!--Navigation-->
        <section id="navbar">
            <a class="close-navbar-toggler collapsed" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation close" role="button"></a>
            <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
                <div class="container pt-2 pb-2">
                    <a class="navbar-brand" href="{% url 'mainsite:index' %}">Online Job Portal</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span><em class="bi bi-list" style="font-size: 30px; color: white;"></em></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                        <ul class="navbar-nav text-end gap-3">
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:index' %}" target="_top">Anasayfa</a></li>
                            {% if not user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'profiles:signup' %}" target="_top">Kullanıcı Kaydı</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'profiles:login' %}" target="_top">Kullanıcı Girişi</a></li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                {% if user.is_recruiter %}
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:job_list' %}" target="_top">İş İlanları</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:job_create' %}" target="_top">İş İlanı Ekle</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:applied_applicants_list' %}" target="_top">İş Başvuruları</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:jobseeker_profiles' %}" target="_top">İş Arayanlar</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'profiles:recruiter_profile' slug=request.user.recruiter.slug %}" target="_top">Profilim</a></li>
                                {% elif user.is_jobseeker %}
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:related_job_list' %}" target="_top">Bana Uygun İş İlanları</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'mainsite:job_list' %}" target="_top">İş İlanları</a></li>
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'profiles:jobseeker_profile' slug=request.user.jobseeker.slug %}" target="_top">Profilim</a></li>
                                {% else %}
                            <li class="nav-item"><a class="nav-link" data-scroll href="http://127.0.0.1:8007/controlme/" target="_top">Admin Paneli</a></li>
                                {% endif %}
                            <li class="nav-item"><a class="nav-link" data-scroll href="{% url 'profiles:logout' %}" target="_top">({{ user.get_username }}) Çıkış Yap</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </section>
        <!--End Navigation-->
    </header>

    <main>
        {% if user.is_authenticated %}
        <div class="container pt-5">
            <div class="row">
                <div class="col">
                    <form onkeyup="checkForm()" autocomplete="off" action="{% url 'mainsite:search_results' %}" method="get" class="d-flex" novalidate>
                        {% csrf_token %}
                        <div class="form-group col-xxl-10 col-xl-10 col-lg-10 col-md-9 col-sm-7 col-8">
                            <label class="d-flex flex-column">
                                <input name="q" type="text" placeholder="Ör: django" required>
                            </label>
                        </div>
                        <div class="form-group col-xxl-2 col-xl-2 col-lg-2 col-md-3 col-sm-5 col-4 ps-2 d-flex flex-column">
                            <button type="submit" class="btn btn-dark btn-sm" id="search_button">İlan Ara</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
        <!--Content-->
        {% block content %}
        {% endblock %}
        <!--End Content-->
    </main>

    <script>
        var inp  = document.getElementsByTagName("input");
        var search_button = document.getElementById("search_button");
        // Disable the button dynamically using javascript
        search_button.disabled = "disabled";

        function checkForm() {
            for (var i = 0; i < inp .length; i++) {
                if (inp [i].checkValidity() === false) {
                    search_button.disabled = "disabled";
                } else {
                    search_button.disabled = false;
                }
            }
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/ckeditor-full@4.7.3/ckeditor.min.js"></script>
</body>
</html>