config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from config import settings

urlpatterns = [
    # MAIN URLS
    path('controlme/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('profiller/', include('profiles.urls')),

    # Reset password urls
    path('sifre-sifirla/', auth_views.PasswordResetView.as_view(template_name='profiles/password_reset.html',
                                                                email_template_name='profiles/password_reset_email.html',
                                                                subject_template_name='profiles/password_reset_subject.txt'), name='password_reset'),
    path('sifre-gonderildi/', auth_views.PasswordResetDoneView.as_view(template_name='profiles/password_reset_done.html'), name='password_reset_done'),
    path('sifre-onayla/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='profiles/password_reset_confirm.html'), name='password_reset_confirm'),
    path('sifre-sifirlandi/', auth_views.PasswordResetCompleteView.as_view(template_name='profiles/password_reset_complete.html'), name='password_reset_complete'),

    # ADDITIONAL URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.urls import path
from mainsite.views import IndexView, JobSeekerProfilesView, JobsView, JobDetailView, JobUpdateView, JobCreateView, \
    AppliedApplicantsView, SearchResultsView, RelatedJobsView

app_name = 'mainsite'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('is-arayanlar/', JobSeekerProfilesView.as_view(), name='jobseeker_profiles'),
    path('is-ilanlari/', JobsView.as_view(), name='job_list'),
    path('ilgili-is-ilanlari/', RelatedJobsView.as_view(), name='related_job_list'),
    path('is-ilanlari/ilan-detayi/<slug:slug>/', JobDetailView.as_view(), name='job_details'),
    path('is-ilanlari/ilan-guncelle/<slug:slug>/', JobUpdateView.as_view(), name='job_update'),
    path('is-ilani-ekle/', JobCreateView.as_view(), name='job_create'),
    path('ilan-basvurulari/', AppliedApplicantsView.as_view(), name='applied_applicants_list'),
    path('arama/', SearchResultsView.as_view(), name='search_results'),
]

profiles/urls.py
from django.urls import path
from profiles import views
from profiles.views import SignUpView, JobSeekerSignUpView, RecruiterSignUpView, \
    JobSeekerProfileUpdateView, JobSeekerProfileView, RecruiterProfileView, RecruiterProfileUpdateView
from django.contrib.auth import views as auth_views


app_name = 'profiles'
urlpatterns = [
    # Log-in and Logout
    path('kayit/', SignUpView.as_view(), name='signup'),
    path('kayit/is-arayan/', JobSeekerSignUpView.as_view(), name='jobseeker_signup'),
    path('kayit/ik-uzmani/', RecruiterSignUpView.as_view(), name='recruiter_signup'),
    path('giris-yap/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('cikis-yap/', auth_views.LogoutView.as_view(), name='logout'),

    # Mainsite urls
    path('is-arayan/profil/<slug:slug>/', JobSeekerProfileView.as_view(), name='jobseeker_profile'),
    path('is-arayan/guncelle/<slug:slug>/', JobSeekerProfileUpdateView.as_view(), name='jobseeker_profile_update'),
    path('ik-uzmani/profil/<slug:slug>/', RecruiterProfileView.as_view(), name='recruiter_profile'),
    path('ik-uzmani/guncelle/<slug:slug>/', RecruiterProfileUpdateView.as_view(), name='recruiter_profile_update'),
    path("ilana-basvur/<int:job_id>/", views.apply_job_view, name="apply_job"),
]

mainsite/models/applicants.py
from django.db import models
from mainsite.models import Job
from profiles.models.jobseeker import JobSeeker


class Applicants(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, verbose_name="İş İlanı", related_name='applicants')
    applicant = models.ForeignKey(JobSeeker, on_delete=models.CASCADE, verbose_name="İş Arayan Profili", related_name='applied')
    date_posted = models.DateTimeField("Başvuru Tarihi", auto_now_add=True)

    def __str__(self):
        return self.applicant.profile.username

    class Meta:
        verbose_name_plural = "Başvuranlar"
        verbose_name = "Başvuru Ekle"
        ordering = ("-date_posted",)

mainsite/models/jobs.py
from django.db import models
from profiles.models.recruiter import Recruiter
from profiles.models.skills import Skill
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from django.urls import reverse
from django.utils.crypto import get_random_string


JOB_INSIGHT_CHOICES = (
    ('Tam Zamanlı', 'Tam Zamanlı'),
    ('Yarı Zamanlı', 'Yarı Zamanlı'),
    ('Uzaktan Tam Zamanlı', 'Uzaktan Tam Zamanlı'),
    ('Uzaktan Yarı Zamanlı', 'Uzaktan Yarı Zamanlı'),
    ('Hibrit', 'Hibrit'),
)


class Job(models.Model):
    is_active = models.BooleanField("Durum (Aktif/Pasif)", default=True)
    job_title = models.CharField("İş İlanı Başlığı", max_length=155)
    company = models.CharField("Firma", max_length=100)
    recruiter = models.ForeignKey(Recruiter, on_delete=models.RESTRICT, verbose_name="IK Uzmanı", related_name='jobs')
    location = models.CharField("Ülke", max_length=100)
    skills_req = models.ManyToManyField(Skill, verbose_name="İstenilen Beceriler")
    job_insight = models.CharField("Çalışma Şekli", max_length=30, choices=JOB_INSIGHT_CHOICES, default='Full Time', null=True)
    description = RichTextUploadingField("İş Açıklaması")
    slug = models.SlugField("Slug", help_text="Bu alan otomatik olarak oluşturulmaktadır.", max_length=60, unique=True, null=True, blank=True, allow_unicode=True)
    updated = models.DateTimeField("Güncellenme Tarihi", auto_now=True)
    date_added = models.DateTimeField("Oluşturulma Tarihi", auto_now_add=True)

    def __str__(self):
        return self.job_title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(get_random_string(length=15) + "-" + str(self.job_title))
        super(Job, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('mainsite:job_details', args=[self.slug])

    class Meta:
        verbose_name_plural = "İş İlanları"
        verbose_name = "İş İlanı Ekle"
        ordering = ("-updated",)

mainsite/forms/job_create_form.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.forms import TextInput
from mainsite.models import Job
from profiles.models import Skill


class JobCreateForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget(), label="İş Açıklaması")
    skills_req = forms.ModelMultipleChoiceField(
        queryset=Skill.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="İstenilen Beceriler"
        )

    class Meta:
        model = Job
        fields = ('job_title', 'company', 'recruiter', 'location', 'job_insight', 'skills_req', 'description')

        widgets = {
            'recruiter': TextInput(attrs={'readonly': 'readonly'}),
        }

mainsite/views/applied_applicants.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from mainsite.models import Applicants
from profiles.models import user_is_recruiter


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_recruiter], name='dispatch')
class AppliedApplicantsView(ListView):
    model = Applicants
    template_name = "mainsite/applied_applicants.html"
    context_object_name = "applicants"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

mainsite/views/index.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "mainsite/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

mainsite/views/job_create.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from mainsite.forms import JobCreateForm
from mainsite.models import Job
from profiles.models import Recruiter, user_is_recruiter


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_recruiter], name='dispatch')
class JobCreateView(CreateView):
    model = Job
    form_class = JobCreateForm
    template_name = 'mainsite/job_create_form.html'

    def get_initial(self):
        user = self.request.user
        initial = super(JobCreateView, self).get_initial()
        initial['recruiter'] = Recruiter.objects.get(profile=user)  # Automatically selects the recruiter in the form.
        return initial

mainsite/views/job_details.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from mainsite.models import Job


@method_decorator([login_required(login_url=reverse_lazy("profiles:login"))], name='dispatch')
class JobDetailView(DetailView):
    model = Job
    template_name = 'mainsite/job_detail.html'
    context_object_name = "job"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

mainsite/views/job_edit.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from mainsite.models import Job
from profiles.models import user_is_recruiter


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_recruiter], name='dispatch')
class JobUpdateView(UpdateView):
    model = Job
    fields = ('job_title', 'company', 'job_insight', 'location', 'skills_req', 'description')
    context_object_name = "job"
    template_name = 'mainsite/job_edit.html'

    def form_valid(self, form):
        messages.success(self.request, 'İş ilanı bilgileri başarıyla güncellendi!')
        return super().form_valid(form)

mainsite/views/jobs.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from mainsite.models import Job


@method_decorator([login_required(login_url=reverse_lazy("profiles:login"))], name='dispatch')
class JobsView(ListView):
    model = Job
    template_name = "mainsite/jobs.html"
    context_object_name = "jobs"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

mainsite/views/jobseeker_profiles.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from profiles.models import JobSeeker, user_is_jobseeker


# @method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_jobseeker], name='dispatch')
class JobSeekerProfilesView(ListView):
    model = JobSeeker
    template_name = "mainsite/jobseeker_profiles.html"
    context_object_name = "jobseekers"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

mainsite/views/related_jobs.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from mainsite.models import Job
from profiles.models import JobSeeker, user_is_jobseeker


@method_decorator([login_required(login_url=reverse_lazy("profiles:login")), user_is_jobseeker], name='dispatch')
class RelatedJobsView(ListView):
    model = Job
    template_name = "mainsite/related_jobs.html"
    context_object_name = "jobs"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_obj = JobSeeker.objects.get(profile_id=self.request.user.id)  # Identifies the user.
        object_list = Job.objects.filter(skills_req__profiles__profile_id=user_obj.pk)  # Returns the skills of the specified user.
        context['related_jobs'] = object_list.distinct()
        return context

mainsite/views/search.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.views.generic import ListView
from mainsite.models import Job


@method_decorator([login_required(login_url=reverse_lazy("profiles:login"))], name='dispatch')
class SearchResultsView(ListView):
    template_name = "mainsite/search_result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            object_list = Job.objects.filter(
                Q(job_title__icontains=query) | Q(skills_req__skill_name__icontains=query)
            ).distinct()
            return object_list

mainsite/templates/mainsite/applied_applicants.html
{% extends 'base.html' %}

{% block title %}Başvurular{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row">
                    <h1 class="text-center">İş Başvuruları</h1>
                    <div class="table-responsive pt-4">
                        <table class="table table-striped table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th>#</th>
                                    <th>İsim</th>
                                    <th>İlan Adı</th>
                                    <th>Başvuru Tarihi</th>
                                    <th>İncele</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for applicant in applicants %}
                                    {% if applicant.job.recruiter.profile.id == user.id %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td class="">{{ applicant.applicant.get_full_name }}</td>
                                    <td>{{ applicant.job.job_title }}</td>
                                    <td>{{ applicant.date_posted }}</td>
                                    <td><a class="btn btn-dark btn-sm" href="{% url 'profiles:jobseeker_profile' applicant.applicant.slug %}" role="button">Profili İncele</a></td>
                                </tr>
                                    {% endif %}
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/index.html
{% extends 'base.html' %}

{% block title %}Anasayfa{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row">
                    <div class="card text-white bg-dark mb-3">
                        <div class="card-header h1 text-center">Baykar Vaka Çalışması</div>
                        <div class="card-body">
                            <h3 class="card-title">PROJE BİLGİ FORMU</h3>
                            <p class="card-text">Farklı alanlardan insan kaynakları uzmanının açık pozisyonlarını tek bir platformda nasıl yayınladığını ve bunun ilgili adaylara nasıl ulaştığını hiç merak ettiniz mi? Django projesi ile iş arama portalı oluşturarak kendiniz öğrenebilirsiniz.
                            <h4 class="card-title">Portal aşağıdaki özellikleri içerecektir</h4>
                            <h5 class="card-title">Kayıt ve oturum açma:</h5>
                            <p>Hem <del>yönetici</del> <mark>iş veren/İK uzmanı</mark> hem de iş arayan taraflarında bir kayıt ve oturum açma sayfası sağlanır. <del>Yönetici</del> <mark>iş veren/İK uzmanı</mark>, <mark>ilan ekleyip-düzenleyebilir, ilan başvurularını görebilir,</mark> kullanıcı kayıtlarını kontrol edebilirken, iş arayan, platformda iş arama, iş başvurusu vb. gibi amaçlanan faaliyetleri kaydolarak veya oturum açarak gerçekleştirebilir. <mark>Projede kullanıcılar için izinler detaylı olarak ele alınmıştır.</mark></p>
                            <p class="card-title"><mark>Gerçek Projede Eklenmesi Gereken Minimum Özellikler:</mark></p>
                            <ol>
                                <li><mark>İlan silme</mark></li>
                                <li><mark>İlan bitiş süresi ekleme</mark></li>
                                <li><mark>İlan için başvuru adayı tercihi belirleyebilme/değiştirebilme</mark></li>
                                <li><mark>IK Uzmanı için uygun personel arayabilme</mark></li>
                                <li><mark>İş arayan için başvurulan ilanlar listesini görebilme</mark></li>
                                <li><mark>İş arayan için ilan başvurusunu geri çekebilme ve bunlar gibi temel özellikler.</mark></li>
                            </ol>
                            <p><mark>Elbette tasarım da olmadığından SEO  için gerekli temel ayarlamalar, özellikler eklenmemiştir. Eklenmiş olarak yaptığım örnek site:</mark> <mark><a href="https://dennled.com/" target="_blank">dennled.com</a></mark></p>
                            <h5 class="card-title">Tercihe göre iş ilanları:</h5>
                            <p>Kullanıcının tercihi, uygulamadaki bir filtreleme mekanizması aracılığıyla toplanabilir. Örneğin, birisi yalnızca bir Django projeleri geliştirici işi istiyorsa, bununla ilgili iş ilanları kişinin akışında görüntülenebilir. <mark>Yaptığım projede kişiye uygun ilanlar, kişinin beceri alanlarına göre otomatik olarak filtrelenerek listelenmektedir.</mark></p>
                            <h5 class="card-title">Profil yönetimi:</h5>
                            <p>Kullanıcı, tercihlerine göre güncelleyerek, silerek veya veri ekleyerek profilini yönetebilmelidir. Bir parola sıfırlama mekanizması da uygulanmalıdır.</p>
                            <h5 class="card-title">Kullanılması istenen minimum teknolojiler:</h5>
                            <ul>
                                <li>Python</li>
                                <li>Django</li>
                                <li>Html</li>
                                <li>Css <mark>Bootstrap CSS Framework kullandım ama CSS biliyorum :)</mark></li>
                                <li>Js</li>
                                <li>Postgresql <mark>Production sürüm haricinde SQLite kullanılması tavsiye edilmektedir. Ancak proje yine de talep üzerine en baştan PostgreSQL ile yapıltı.</mark></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/job_create_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}İş İlanı Ekle{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center ">
                    <h1 class="text-center">İş İlanı Ekle</h1>
                    <div class="col-6 pt-4">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.media }}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-5" type="submit">Ekle</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/job_detail.html
{% extends 'base.html' %}
{% load is_already_applied %}

{% block title %}İş İlanı Detayları{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center">
                    <h1 class="text-center">İş İlanı Detayları</h1>
                    <div class="col-6 pt-4">
                        <div>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success text-center" role="alert">
                                        {% if message.tags %}
                                            <p>{{ message }}</p>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <p><strong>İlan Başlığı:</strong> {{ job.job_title }}</p>
                            <p><strong>İlan Tarihi:</strong> {{ job.date_added }}</p>
                            <p><strong>Firma:</strong> {{ job.company }}</p>
                            <p><strong>IK Uzmanı:</strong> {{ job.recruiter.get_full_name }}</p>
                            <p><strong>Çalışma Şekli:</strong> {{ job.job_insight }}</p>
                            <p><strong>Ülke:</strong> {{ job.location }}</p>
                            <p><strong>İstenilen Beceriler:</strong>
                            {% for skill in job.skills_req.all %}
                                {{ skill }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </p>
                            <p><strong>İlan Detayları:</strong> {{ job.description|safe }}</p>

                            {% if user.is_authenticated and job.recruiter.profile.id == user.id %}
                            <a href="{% url 'mainsite:job_update' slug=job.slug %}" class="btn btn-dark mb-5" role="button">İlanı Güncelle</a>
                            {% endif %}

                            {% if user.is_authenticated and not user.is_recruiter %}
                            {% is_already_applied job user.id as is_applied %}
                                {% if is_applied %}
                                <button type="button" class="btn btn-danger disabled">Başvuruldu</button>
                                {% else %}
                                <form action="{% url 'profiles:apply_job' job.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <input type="submit" class="btn btn-success mb-5" value="Başvur"/>
                                </form>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/job_edit.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}İş İlanı Güncelleme{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row d-flex justify-content-center ">
                    <h1 class="text-center">İş İlanı Güncelle</h1>
                    <div class="col-6 pt-4">
                        {% if job.recruiter.profile.id == user.id %}
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.media }}
                            {{ form|crispy }}
                            <button class="btn btn-dark mt-3 mb-5" type="submit">Güncelle</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/jobs.html
{% extends 'base.html' %}
{% load is_already_applied %}

{% block title %}İş İlanları{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row">
                    <h1 class="text-center">İş İlanları</h1>
                    {% for job in jobs %}
                    <div class="col-4 pt-4">
                        <div class="card mb-3">
                            <div class="row g-0">
                                <div class="col">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ job.job_title }}</h5>
                                        <p class="card-text">{{ job.company }} - {{ job.job_insight }}</p>
                                        <p class="card-text text-muted">Gereksinimler:
                                            {% for skill in job.skills_req.all %}
                                            {{ skill }}{% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        </p>
                                        <p class="card-text">{{ job.description|striptags|escape|truncatechars:120 }}</p>
                                        <a href="{{ job.get_absolute_url }}" class="btn btn-primary">İlanı Görüntüle</a>
                                        {% if user.is_authenticated %}
                                            {% is_already_applied job user.id as is_applied %}
                                            {% if is_applied %}
                                                <button type="button" class="btn btn-danger disabled">Başvuruldu</button>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/jobseeker_profiles.html
{% extends 'base.html' %}
{% load static %}

{% block title %}İş Arayan Kullanıcılar{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row">
                    <h1 class="text-center">İş Arayanlar</h1>
                    {% for jobseeker in jobseekers %}
                    <div class="col-4 pt-4">
                        <div class="card">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img class="img-fluid rounded-start" src="{% if jobseeker.avatar %}{% get_media_prefix %}{{ jobseeker.avatar_thumbnail_140x140 }}{% else %}{% static "/img/no-img.webp" %}{% endif %}" alt="{{ jobseeker.get_full_name }}">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ jobseeker.get_full_name }}</h5>
                                        <p class="card-text text-muted">{{ jobseeker.profession_title }} - {{ jobseeker.country }}</p>
                                        <a href="{{ jobseeker.get_absolute_url }}" class="btn btn-primary">Profili Görüntüle</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}

mainsite/templates/mainsite/related_jobs.html
{% extends 'base.html' %}
{% load is_already_applied %}

{% block title %}İş İlanları{% endblock %}

{% block content %}
        <!--Content-->
        <section id="content">
            <div class="container pt-5">
                <div class="row">
                    <h1 class="text-center">İş İlanları</h1>
                    {% for job in related_jobs %}
                    <div class="col-4 pt-4">
                        <div class="card mb-3">
                            <div class="row g-0">
                                <div class="col">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ job.job_title }}</h5>
                                        <p class="card-text">{{ job.company }} - {{ job.job_insight }}</p>
                                        <p class="card-text text-muted">Gereksinimler:
                                            {% for skill in job.skills_req.all %}
                                            {{ skill }}{% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        </p>
                                        <p class="card-text">{{ job.description|striptags|escape|truncatechars:120 }}</p>
                                        <a href="{{ job.get_absolute_url }}" class="btn btn-primary">İlanı Görüntüle</a>
                                        {% if user.is_authenticated %}
                                            {% is_already_applied job user.id as is_applied %}
                                            {% if is_applied %}
                                                <button type="button" class="btn btn-danger disabled">Başvuruldu</button>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!--End Content-->
{% endblock %}